title: Best of Machine Learning
email: support@remoteml.com
description: >- 
  The best resources about Machine Learning & AI
baseurl: ""
url: "https://bestofml.com"
analytics-id: UA-108818402-5
github: RemoteML/bestofml
maintainers:
  - dmonn

plugins:
  - jekyll-assets
  - kramdown
  - uglifier

source: src
destination: www
markdown: kramdown

cards:
  data: resources         # yaml file in _data (without .yml)
  comments: false
  group_by:
    name: category      # field in yaml to group by
    caption: category  # name of category (ex: industries)
    fa-icon: folder-open
    fa-style: far        # valid: fas (solid), far (regular), fal (light), fab (brand)
  meta:               # use this section to display card info, in addition to 'group_by'
    - name: tags
      caption: tags
      fa-icon: tags
      fa-style: fa
    - name: url
      caption: www
      fa-icon: globe
      fa-style: fas


compress_html:
  ignore:
    envs: ["development"]
  clippings: []
  comments: all
  endings: []
  startings: []
  blanklines: false
  profile: false

assets:
  sources:
  - _assets/vendor
  digest: true
  compression: true
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  compress:
    css: false
    js: uglifier

include:
  - CNAME